version: '2'
services:
  odoo11:
    image: odoo:11.0
    ports:
      - "3389:8069"
    tty: true
    command: -- --dev=reload
#    command: odoo scaffold /mnt/extra-addons/test_module
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
